package view;

import java.awt.Color;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.UIManager;
import javax.swing.border.EmptyBorder;

import main.Shop;
import model.Product;

public class ExpiredProductView extends JFrame implements ActionListener {

	private static final long serialVersionUID = 1L;
	private Shop shop;
	private JTextField prodNameField;
	private JButton btnAccept;
	private JButton btnCancel;

	/**
	 * Create the frame.
	 */
	public ExpiredProductView(Shop shop) {
		this.shop = shop;
		productExpiredUI();
	}

	private void productExpiredUI() {
		UIManager.put("OptionPane.okButtonText", "OK");
		setTitle("Product expired menu");
		setSize(310, 115);
		setLocationRelativeTo(null);
		setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);

		// text fields and login button
		prodNameField = new JTextField(10);

		btnAccept = new JButton("OK");
		btnCancel = new JButton("Cancel");

		// panel settings
		JPanel panel = new JPanel();
		panel.setBackground(new Color(248, 249, 250));
		panel.setBorder(new EmptyBorder(10, 10, 10, 10));
		panel.setLayout(null);

		// labels and input fields
		JLabel nameLabel = new JLabel("Product name:");
		nameLabel.setBounds(10, 10, 100, 20);
		prodNameField.setBounds(120, 10, 166, 20);

		btnAccept.setBounds(120, 40, 83, 30);
		btnCancel.setBounds(213, 40, 73, 30);

		// setting button fonts
		Font buttonFont = new Font("Arial", Font.BOLD, 12);
		setButtonFonts(new JButton[] { btnAccept, btnCancel }, buttonFont);

		// setting button backgrounds
		Color buttonBackgroundColor = new Color(233, 236, 239);
		setButtonBackgrounds(new JButton[] { btnAccept, btnCancel }, buttonBackgroundColor);

		// setting frame background
		panel.setBackground(new Color(248, 249, 250));

		// adding components to the panel
		panel.add(nameLabel);
		panel.add(prodNameField);
		panel.add(btnAccept);
		panel.add(btnCancel);

		// adding ActionListener to accept or cancel
		btnAccept.addActionListener(this);
		btnCancel.addActionListener(this);

		// adding the panel to the frame
		getContentPane().add(panel);

	}

	/**
	 * Sets the font for a group of buttons.
	 *
	 * @param buttons the array of JButtons to set the font for
	 * @param font    the font to set
	 */
	private void setButtonFonts(JButton[] buttons, Font font) {
		for (JButton button : buttons) {
			button.setFont(font);
		}
	}

	/**
	 * Sets the background color for a group of buttons.
	 *
	 * @param buttons the array of JButtons to set the background color for
	 * @param color   the color to set as the background
	 */
	private void setButtonBackgrounds(JButton[] buttons, Color color) {
		for (JButton button : buttons) {
			button.setBackground(color);
		}
	}

	/**
	 * Handles action events generated by the buttons in the dialog window.
	 */
	@Override
	public void actionPerformed(ActionEvent e) {
		String name = prodNameField.getText();

		// send product to the shop method with the parameter
		Product product = shop.findProduct(name);

		// if the product exist add stock
		if (product != null) {
			product.expire();

			// show an informational message
			JOptionPane.showMessageDialog(this, "Price updated to " + product.getPublicPrice() + ".", "Information",
					JOptionPane.INFORMATION_MESSAGE);
			dispose();
		} else {
			JOptionPane.showMessageDialog(this, "The product does not exist in the inventory.", "Error",
					JOptionPane.ERROR_MESSAGE);
		}
	}

}
