package view;

import java.awt.Color;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.UIManager;
import javax.swing.border.EmptyBorder;

import main.Shop;
import model.Product;

public class ExpiredProductView extends JFrame implements ActionListener {

    private static final long serialVersionUID = 1L;

    // Fields
    private Shop shop;
    private JTextField prodNameField;
    private JButton btnAccept;
    private JButton btnCancel;

    /**
     * Create the frame.
     */
    public ExpiredProductView(Shop shop) {
        this.shop = shop;
        initializeUI();
    }

    /**
     * Initializes the product expired UI.
     */
    private void initializeUI() {
        UIManager.put("OptionPane.okButtonText", "OK");
        setTitle("Product expired menu");
        setSize(310, 115);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);

        // Initialize components
        createComponents();

        // Add components to the panel
        JPanel panel = createPanel();
        getContentPane().add(panel);
    }

    /**
     * Creates and sets up the components for the dialog.
     */
    private void createComponents() {
        prodNameField = new JTextField(10);

        btnAccept = new JButton("OK");
        btnCancel = new JButton("Cancel");

        // Configure buttons
        configureButton(btnAccept);
        configureButton(btnCancel);
    }

    /**
     * Configures the button with font and background color.
     *
     * @param button The button to configure.
     */
    private void configureButton(JButton button) {
        button.setFont(new Font("Arial", Font.BOLD, 12));
        button.setBackground(new Color(233, 236, 239));
        button.addActionListener(this);
    }

    /**
     * Creates the panel and adds components to it.
     *
     * @return The created JPanel.
     */
    private JPanel createPanel() {
        JPanel panel = new JPanel();
        panel.setBackground(new Color(248, 249, 250));
        panel.setBorder(new EmptyBorder(10, 10, 10, 10));
        panel.setLayout(null);

        // Create and position labels and fields
        JLabel nameLabel = new JLabel("Product name:");
        nameLabel.setBounds(10, 10, 100, 20);
        prodNameField.setBounds(120, 10, 166, 20);

        btnAccept.setBounds(120, 40, 83, 30);
        btnCancel.setBounds(213, 40, 73, 30);

        // Add components to the panel
        panel.add(nameLabel);
        panel.add(prodNameField);
        panel.add(btnAccept);
        panel.add(btnCancel);

        return panel;
    }

    /**
     * Handles action events generated by the buttons in the dialog window.
     */
    @Override
    public void actionPerformed(ActionEvent e) {
        String name = prodNameField.getText();
        Product product = shop.findProduct(name);

        if (product != null) {
            product.expire();
            JOptionPane.showMessageDialog(this, "Price updated to " + product.getPublicPrice() + ".", "Information",
                    JOptionPane.INFORMATION_MESSAGE);
            dispose();
        } else {
            JOptionPane.showMessageDialog(this, "The product does not exist in the inventory.", "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }
}
